### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by dnarkorn** [RoySpino/RB_SNS_VSCodeExtentions#1]
currently VSCode I have default to Code for IBM i extension, how do I use your extension?  Thanks.

**Comment by RoySpino** [comment]
For fixed format code:

1. The issue is with column positioning. I assume when you copy your code there are five spaces before the spec column. if so remove those spaces. My extension requires that the spec column begins at column 1 not on column 6.
2. This however is not the case if you are viewing RPG3 code that code requires five spaces 

For Free format code:

1. make sure that the code always starts with **free beginning on column 1. 
2. Or when you use /free or /end-free that you add a space (or spec) on column 1 before adding the tag

If this does not help then its most likely a conflict between my extension and IBMi Languages extension.
I will try to move the spec column to position 6. But I prefer it to start on position 1 because that's how I see it in SEU.

**Comment by RoySpino** [comment]
New update is on its way.
Highlighting will now begin on either column 6 or column 1. You will not need to do anything other than copy or open the file in VS Code. 
RPG3 code will not get this feature, it will still start at column 6.

Let me know if there are any problems.
